go_import_path: github.com/FZambia/viper-lite

language: go
go:
  - 1.6.3
  - 1.7
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go install ./...
  - go test -v ./...

sudo: false
